<a href="https://colab.research.google.com/github/rrozati/Public/blob/master/sudoku_solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
#### python sudoky solver
import numpy as np
import sys

In [13]:
grid1 = [[5,3,0,0,7,0,0,0,0],
    [6,0,0,1,9,5,0,0,0],
		[0,9,8,0,0,0,0,6,0],
		[8,0,0,0,6,0,0,0,3],
		[4,0,0,8,0,3,0,0,1],
		[7,0,0,0,2,0,0,0,6],
		[0,6,0,0,0,0,2,8,0],
		[0,0,0,4,1,9,0,0,5],
		[0,0,0,0,8,0,0,7,9]]
		
grid2 = [[0,0,0,0,0,0,0,0,0],
        [0,0,0,0,0,0,0,0,0],
		    [0,0,0,0,0,0,0,0,0],
	    	[3,8,4,0,0,0,0,0,0],
		    [0,0,0,0,0,0,0,0,0],
		    [0,0,0,0,0,0,0,0,0],
		    [0,0,0,0,0,0,0,0,0],
		    [0,0,0,0,0,0,0,0,0],
		    [0,0,0,0,0,0,0,0,2]]

grid = [[0,0,0,9,0,1,5,0,2],
        [7,5,0,0,0,0,0,0,0],
		    [0,2,0,7,3,0,0,0,4],
	    	[3,0,0,0,0,0,2,0,0],
		    [0,0,6,0,2,0,7,0,0],
		    [0,0,2,0,0,0,0,0,9],
		    [2,0,0,0,4,6,0,5,0],
		    [0,0,0,0,0,0,0,6,1],
		    [6,0,9,1,0,3,0,0,0]]

grid


[[0, 0, 0, 9, 0, 1, 5, 0, 2],
 [7, 5, 0, 0, 0, 0, 0, 0, 0],
 [0, 2, 0, 7, 3, 0, 0, 0, 4],
 [3, 0, 0, 0, 0, 0, 2, 0, 0],
 [0, 0, 6, 0, 2, 0, 7, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0, 9],
 [2, 0, 0, 0, 4, 6, 0, 5, 0],
 [0, 0, 0, 0, 0, 0, 0, 6, 1],
 [6, 0, 9, 1, 0, 3, 0, 0, 0]]

In [9]:
def possible( x,y, n):
	global grid
	for i in range(0,9):
		if grid[x][i] == n :
			return False
	for i in range(0,9):
		if grid[i][y] == n :
			return False
	x0 = (x//3)*3
	y0 = (y//3)*3
	for i in range(0,3):
		for j in range(0,3):
			if grid[x0+i][y0+j] == n:
				return False
	return True


In [7]:
possible(4,4,5)

True

In [5]:
def validate():
	global grid
	txy = 0
	tyx = 0
	for x in range(9):
		for y in range(9):
			txy += grid[x][y]
			tyx += grid[y][x]
		if txy != 45 or tyx != 45:
			return False
		txy = 0
		tyx = 0
	q1 = 0 
	q2 = 0 
	q3 = 0
	for z in range(0,9,3):
		for x in range(0,3):
			for y in range(0,3):
				q1 += grid[x][z+y]
				q2 += grid[3+x][z+y]
				q3 += grid[6+x][z+y]
		if q1 + q2 + q3 != 135:
			return False
		q1 = 0 
		q2 = 0 
		q3 = 0
	return True	

def solve():
	global grid
	for x in range(9):
		for y in range(9):
			if grid[x][y] == 0:
				for n in range(1,10):
					if possible(x,y,n):
						grid[x][y] = n
						solve()
						grid[x][y] = 0;
				return		
	print(np.matrix(grid))
	print(validate() )
	x = input("More ?")
	if x=="n":
		sys.exit()

In [15]:
solve()



[[4 6 3 9 8 1 5 7 2]
 [7 5 1 4 6 2 3 9 8]
 [9 2 8 7 3 5 6 1 4]
 [3 7 4 5 1 9 2 8 6]
 [1 9 6 3 2 8 7 4 5]
 [5 8 2 6 7 4 1 3 9]
 [2 1 7 8 4 6 9 5 3]
 [8 3 5 2 9 7 4 6 1]
 [6 4 9 1 5 3 8 2 7]]
True
More ?j
